eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8962
spring:
  application:
    name: service-hi

    
minio:
  endpoint: http://192.168.92.1:9000/
  accessKey: root
  secretKey: root1234
  bucketName: bucketName